spring.application.name=JavaTaskScheduler
spring.profiles.active=dev
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/task_scheduler
spring.datasource.username=postgres
spring.datasource.password=your_password

# Don't let Hibernate overwrite your beautiful SQL schema!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
